import type { Product, Certification } from "@/types/product";

export const COMPANY_INFO = {
  razonSocial: "Business Beans Perú SRL",
  ruc: "20XXXXXXXXX",
  direccion: "Av. Ejemplo 123, Lima, Perú",
  email: "info@businessbeans.com",
  telefono: "+51 920 833 371",
  website: "www.businessbeans.com",
} as const;

export const PRODUCTS: Product[] = [
  {
    id: "frijol-canario",
    nameKey: "products.items.frijol-canario.name",
    shortDescriptionKey: "products.items.frijol-canario.shortDescription",
    descriptionKey: "products.items.frijol-canario.description",
    tariffCode: "0713.33.90.00",
    availability: "all-year",
    seasonalityKey: "products.items.frijol-canario.seasonality",
    destinationsKey: "products.items.frijol-canario.destinations",
    certificationsKey: "products.items.frijol-canario.certifications",
  },
  {
    id: "pallar-baby",
    nameKey: "products.items.pallar-baby.name",
    shortDescriptionKey: "products.items.pallar-baby.shortDescription",
    descriptionKey: "products.items.pallar-baby.description",
    tariffCode: "0713.22.00.00",
    availability: "seasonal",
    seasonalityKey: "products.items.pallar-baby.seasonality",
    destinationsKey: "products.items.pallar-baby.destinations",
    certificationsKey: "products.items.pallar-baby.certifications",
  },
  {
    id: "lenteja-verde",
    nameKey: "products.items.lenteja-verde.name",
    shortDescriptionKey: "products.items.lenteja-verde.shortDescription",
    descriptionKey: "products.items.lenteja-verde.description",
    tariffCode: "0713.40.00.00",
    availability: "all-year",
    seasonalityKey: "products.items.lenteja-verde.seasonality",
    destinationsKey: "products.items.lenteja-verde.destinations",
    certificationsKey: "products.items.lenteja-verde.certifications",
  },
  {
    id: "frijol-castilla",
    nameKey: "products.items.frijol-castilla.name",
    shortDescriptionKey: "products.items.frijol-castilla.shortDescription",
    descriptionKey: "products.items.frijol-castilla.description",
    tariffCode: "0713.33.20.00",
    availability: "seasonal",
    seasonalityKey: "products.items.frijol-castilla.seasonality",
    destinationsKey: "products.items.frijol-castilla.destinations",
    certificationsKey: "products.items.frijol-castilla.certifications",
  },
  {
    id: "garbanzo",
    nameKey: "products.items.garbanzo.name",
    shortDescriptionKey: "products.items.garbanzo.shortDescription",
    descriptionKey: "products.items.garbanzo.description",
    tariffCode: "0713.20.00.00",
    availability: "seasonal",
    seasonalityKey: "products.items.garbanzo.seasonality",
    destinationsKey: "products.items.garbanzo.destinations",
    certificationsKey: "products.items.garbanzo.certifications",
  },
  {
    id: "maiz-gigante-cusco",
    nameKey: "products.items.maiz-gigante-cusco.name",
    shortDescriptionKey: "products.items.maiz-gigante-cusco.shortDescription",
    descriptionKey: "products.items.maiz-gigante-cusco.description",
    tariffCode: "1005.90.20.00",
    availability: "seasonal",
    seasonalityKey: "products.items.maiz-gigante-cusco.seasonality",
    destinationsKey: "products.items.maiz-gigante-cusco.destinations",
    certificationsKey: "products.items.maiz-gigante-cusco.certifications",
  },
];

export const CERTIFICATIONS: Certification[] = [
  {
    id: "fda",
    icon: "shield",
    nameKey: "home.certifications.items.fda.name",
    descriptionKey: "home.certifications.items.fda.description",
  },
  {
    id: "senasa",
    icon: "check-circle",
    nameKey: "home.certifications.items.senasa.name",
    descriptionKey: "home.certifications.items.senasa.description",
  },
  {
    id: "haccp",
    icon: "award",
    nameKey: "home.certifications.items.haccp.name",
    descriptionKey: "home.certifications.items.haccp.description",
  },
];
